# Shape Manipulation

In [1]:
import numpy as np

## Changing the shape of an array
The shape of an array can be changed with various commands. 

Note that the following three commands all return a modified array, but do not change the original array:
- ravel()
- reshape(numrows, numcols)
- T

Note than the follwoing command modifiey the array itself.
- resize((numrows, numcols))

In [2]:
a = np.floor(10*np.random.random((3,4)))
a

array([[ 9.,  3.,  6.,  4.],
       [ 8.,  3.,  3.,  9.],
       [ 6.,  4.,  5.,  1.]])

In [3]:
a.ravel()  # returns the array, flattened

array([ 9.,  3.,  6.,  4.,  8.,  3.,  3.,  9.,  6.,  4.,  5.,  1.])

In [4]:
a.reshape(2, 6)  # returns the array with a modified shape

array([[ 9.,  3.,  6.,  4.,  8.,  3.],
       [ 3.,  9.,  6.,  4.,  5.,  1.]])

In [5]:
a.T  # returns the array, transposed

array([[ 9.,  8.,  6.],
       [ 3.,  3.,  4.],
       [ 6.,  3.,  5.],
       [ 4.,  9.,  1.]])

In [6]:
a.shape  # Do not change the original array.

(3, 4)

In [7]:
a.resize((2, 6))  # Modified the array itself.
a

array([[ 9.,  3.,  6.,  4.,  8.,  3.],
       [ 3.,  9.,  6.,  4.,  5.,  1.]])

In [8]:
a.shape

(2, 6)

## Stacking together different arrays
Several arrays can be stacked together along different axes:
- vstack((a, b)) 
- hstack((a, b))
- column_stack((a, b)) 
- concatenate((a, b), axis=0/1/2...) 
- c_
- r_

In [9]:
a = np.floor(10*np.random.random((2,2)))
a

array([[ 0.,  2.],
       [ 1.,  9.]])

In [10]:
b = np.floor(10*np.random.random((2,2)))
b

array([[ 9.,  9.],
       [ 9.,  3.]])

In [11]:
np.vstack((a,b))  # vertical stack

array([[ 0.,  2.],
       [ 1.,  9.],
       [ 9.,  9.],
       [ 9.,  3.]])

In [12]:
np.hstack((a,b))  # horizontal stack

array([[ 0.,  2.,  9.,  9.],
       [ 1.,  9.,  9.,  3.]])

The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to vstack only for 1D arrays:

In [13]:
np.column_stack((a,b))   # With 2D arrays, like hstack().

array([[ 0.,  2.,  9.,  9.],
       [ 1.,  9.,  9.,  3.]])

In [14]:
a = np.array([4.,2.])
b = np.array([1.,8.])
np.column_stack((a, b))  # With 1D arrays, just like vstack(), but have some differences.

array([[ 4.,  1.],
       [ 2.,  8.]])

In [15]:
np.vstack((a, b))  # 

array([[ 4.,  2.],
       [ 1.,  8.]])

In [16]:
np.column_stack((a[:,np.newaxis],b[:,np.newaxis]))

array([[ 4.,  1.],
       [ 2.,  8.]])

In [17]:
np.vstack((a[:,np.newaxis],b[:,np.newaxis]))

array([[ 4.],
       [ 2.],
       [ 1.],
       [ 8.]])

In [18]:
np.concatenate((a, b))

array([ 4.,  2.,  1.,  8.])

## Splitting one array into several smaller ones
- numpy.vsplit(ary, indices_or_sections)
- numpy.hsplit(ary, indices_or_sections)
- numpy.array_split(ary, indices_or_sections, axis=0)

In [19]:
a = np.floor(10*np.random.random((4,9)))
a

array([[ 0.,  8.,  7.,  6.,  1.,  0.,  5.,  6.,  5.],
       [ 0.,  6.,  3.,  3.,  6.,  8.,  7.,  1.,  8.],
       [ 1.,  2.,  0.,  5.,  1.,  3.,  0.,  0.,  2.],
       [ 5.,  8.,  9.,  5.,  8.,  1.,  8.,  3.,  4.]])

In [20]:
np.hsplit(a, 3)

[array([[ 0.,  8.,  7.],
        [ 0.,  6.,  3.],
        [ 1.,  2.,  0.],
        [ 5.,  8.,  9.]]), array([[ 6.,  1.,  0.],
        [ 3.,  6.,  8.],
        [ 5.,  1.,  3.],
        [ 5.,  8.,  1.]]), array([[ 5.,  6.,  5.],
        [ 7.,  1.,  8.],
        [ 0.,  0.,  2.],
        [ 8.,  3.,  4.]])]

In [21]:
np.hsplit(a,(3, 5))   # Split a after the third and the fourth column

[array([[ 0.,  8.,  7.],
        [ 0.,  6.,  3.],
        [ 1.,  2.,  0.],
        [ 5.,  8.,  9.]]), array([[ 6.,  1.],
        [ 3.,  6.],
        [ 5.,  1.],
        [ 5.,  8.]]), array([[ 0.,  5.,  6.,  5.],
        [ 8.,  7.,  1.,  8.],
        [ 3.,  0.,  0.,  2.],
        [ 1.,  8.,  3.,  4.]])]

In [22]:
np.vsplit(a, 2)

[array([[ 0.,  8.,  7.,  6.,  1.,  0.,  5.,  6.,  5.],
        [ 0.,  6.,  3.,  3.,  6.,  8.,  7.,  1.,  8.]]),
 array([[ 1.,  2.,  0.,  5.,  1.,  3.,  0.,  0.,  2.],
        [ 5.,  8.,  9.,  5.,  8.,  1.,  8.,  3.,  4.]])]

In [23]:
np.array_split(a, 2, axis=0)

[array([[ 0.,  8.,  7.,  6.,  1.,  0.,  5.,  6.,  5.],
        [ 0.,  6.,  3.,  3.,  6.,  8.,  7.,  1.,  8.]]),
 array([[ 1.,  2.,  0.,  5.,  1.,  3.,  0.,  0.,  2.],
        [ 5.,  8.,  9.,  5.,  8.,  1.,  8.,  3.,  4.]])]

In [24]:
np.array_split(a, 3, axis=1)

[array([[ 0.,  8.,  7.],
        [ 0.,  6.,  3.],
        [ 1.,  2.,  0.],
        [ 5.,  8.,  9.]]), array([[ 6.,  1.,  0.],
        [ 3.,  6.,  8.],
        [ 5.,  1.,  3.],
        [ 5.,  8.,  1.]]), array([[ 5.,  6.,  5.],
        [ 7.,  1.,  8.],
        [ 0.,  0.,  2.],
        [ 8.,  3.,  4.]])]