# Copies and Views

In [1]:
import numpy as np

When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. 

There are three cases:

## No copy at all

Simple assignments make no copy of array objects or of their data.

In [2]:
a = np.arange(12)
b = a            # no new object is created
b is a           # a and b are two names for the same ndarray object

True

Python passes mutable objects as references, so function calls make no copy.

In [3]:
def f(x):
    print(id(x))

id(a)                           # id is a unique identifier of an object

139721997284496

In [4]:
f(a)

139721997284496


## View or Shallow Copy

Different array objects can share the same data. The view method creates a new array object that looks at the same data.

In [5]:
c = a.view()
c is a

False

In [6]:
c.base is a

True

In [7]:
a.resize(3, 4)
c.resize(2, 6)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [9]:
c[0,4] = 123
a

array([[  0,   1,   2,   3],
       [123,   5,   6,   7],
       [  8,   9,  10,  11]])

## Deep Copy

The copy method makes a complete copy of the array and its data.

In [10]:
d = a.copy()
d is a

False

In [11]:
d.base is a

False

In [12]:
d[0, 0] = 999
a

array([[  0,   1,   2,   3],
       [123,   5,   6,   7],
       [  8,   9,  10,  11]])