# Linear Algebra

Work in progress. Basic linear algebra to be included here. For more, see `numpy/linalg.py`

## Simple array operations

In [1]:
import numpy as np
a = np.array([[1. , 2.], [3., 4.]])
print(a)

[[ 1.  2.]
 [ 3.  4.]]


In [2]:
a.transpose() # np.transpose(a)

array([[ 1.,  3.],
       [ 2.,  4.]])

In [3]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [4]:
u = np.eye(2)  # unit 2x2 matrix; "eye" represents "I"
u

array([[ 1.,  0.],
       [ 0.,  1.]])

In [5]:
j = np.array([[0., -1.], [1., 0.]])
j

array([[ 0., -1.],
       [ 1.,  0.]])

In [6]:
np.dot(j, j)

array([[-1.,  0.],
       [ 0., -1.]])

In [7]:
np.trace(u)

2.0

In [8]:
y = np.array([[5.], [7.]])
np.linalg.solve(a, y)

array([[-3.],
       [ 4.]])

In [9]:
np.linalg.solve(a, y)  # Solve a linear matrix equation, or system of linear scalar equations, `ax = b`.

array([[-3.],
       [ 4.]])

In [10]:
np.allclose(np.dot(a, np.linalg.solve(a, y)), y)  # Check that the solution is correct

True

In [11]:
np.linalg.eig(j)  # Compute the eigenvalues and right eigenvectors of a square array.

(array([ 0.+1.j,  0.-1.j]),
 array([[ 0.70710678+0.j        ,  0.70710678-0.j        ],
        [ 0.00000000-0.70710678j,  0.00000000+0.70710678j]]))

In [12]:
np.linalg.det(a)  #  Compute the determinant of an array.

-2.0000000000000004

## Using package numpy.linalg

In [13]:
help(np.linalg)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

DESCRIPTION
    Core Linear Algebra Tools
    -------------------------
    Linear algebra basics:
    
    - norm            Vector or matrix norm
    - inv             Inverse of a square matrix
    - solve           Solve a linear system of equations
    - det             Determinant of a square matrix
    - lstsq           Solve linear least-squares problem
    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition
    - matrix_power    Integer power of a square matrix
    
    Eigenvalues and decompositions:
    
    - eig             Eigenvalues and vectors of a square matrix
    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix
    - eigvals         Eigenvalues of a square matrix
    - eigvalsh        Eigenvalues of a Hermitian matrix
    - qr              QR decomposition of a matrix
    - svd             Singular value decomposition 